name: ct484_project


description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  provider: ^6.0.3
  flutter_dotenv: ^5.1.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  loading_animation_widget: ^1.2.0+4
  carousel_slider: ^4.0.0
  # flutter_animated_button: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts: 
    - family: Recoleta
      fonts:
        - asset: assets/font/CooperMdBT-Italic.ttf